version: "3.8"

services:
  matchmaker-redis:
    image: redis:latest
    container_name: matchmaker-redis
    ports:
      - "6379:6379"
    restart: always

  gateway:
    build: ./gateway
    environment:
      - REDIS_URL=redis://matchmaker-redis/
    depends_on:
      - matchmaker-redis
    restart: always

  matchmaker:
    build: ./matchmaker
    env_file:
      - ./matchmaker/.env
    environment:
      - REDIS_ADDR=matchmaker-redis:6379
    depends_on:
      - matchmaker-redis
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "3000:3000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gateway
    restart: always
